services:
  mongo:
    image: mongo:latest
    container_name: chatbot-telegram-mongo-1
    networks:
      - botnet
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db

  bot:
    build:
      context: .
    container_name: chatbot-telegram-bot-1
    networks:
      - botnet
    environment:
      - MONGO_URI=mongodb://mongo:27017/bot_database
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

networks:
  botnet:

volumes:
  mongo-data: